version: '3.8'
services:
  postgres:
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=t-pop-db
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5

  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: t-pop-api
  #   environment:
  #     - PORT=${PORT}
  #     - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/t-pop-db-db
  #   ports:
  #     - '3000:3000'
  #   depends_on:
  #     - postgres
  #   volumes:
  #     - ./src:/app/src
  #   command: bash -c "npx prisma generate && npm run migrate:postgres && npx prisma db seed && npm run start"
volumes:
  postgres:
